### ISSUE TITLE
Fail to split

### ISSUE THREAD

**Issue by ChangWanHong** [hari-rangarajan/CCTree#3]
I loaded some big cscope database, then it prints below and fails. (Reproduced on OSX yosemite).

CCTree: split: illegal option -- C
usage: split [-a sufflen] [-b byte_count] [-l line_count] [-p pattern]
             [file [prefix]]
Shell command: split -C 40000000 cscope.out /var/folders/mb/hpddy_z501d4xhrv86hr5ttc0000gn/T/v7ZumIv/4 failed! Refer help to setup split/join utils.

Cscope database was for chromium project(huge..). 
I read man page of "split", it doesn't have -C option..
Do you know anything about this error?

**Comment by hari-rangarajan** [comment]
If you look in the docs:

"                Option for splitting files (-C or -l)
"                            g:CCTreeSplitProgOption = '-C'
"                 If split program does not support -C, then this parameter must be set to
"                 the number of lines in the split files

Looks like -b is the option for OS X
http://ss64.com/osx/split.html
